HairSalon/Models/Stylist.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using HairSalon;
namespace HairSalon.Models
{
    public class Stylist
    {
        public string FirstName {get;set;}
        public string LastName {get;set;}
        public int Id {get;set;}

        public Stylist(string firstName = "default", string lastName = "default")
        {
            FirstName = firstName;
            LastName = lastName;
        }

       public override bool Equals(System.Object otherItem)
        {
            if (!(otherItem is Stylist))
            {
                return false;
            }
            else
            {
                Stylist newStylist = (Stylist) otherItem;
                bool nameEquality = (this.FirstName == newStylist.FirstName && this.LastName == newStylist.LastName);
                bool idEquality = (this.Id == newStylist.Id);
                return (nameEquality && idEquality);
            }
        }

        public static void ClearAllStylists()
        {
            MySqlConnection conn = DB.Connection();
            conn.Open();
            MySqlCommand cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"DELETE FROM stylists;";
            cmd.ExecuteNonQuery();
            DB.Close(conn);
        }

        public static List<Stylist> GetAll()
        {
            List<Stylist> stylists = new List<Stylist>{};
            MySqlConnection conn = DB.Connection();
            conn.Open();
            var cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"SELECT * FROM stylists;";
            MySqlDataReader rdr = cmd.ExecuteReader() as MySqlDataReader;
            while(rdr.Read())
            {
                Stylist newStylist = new Stylist();
                newStylist.Id = rdr.GetInt32(0);
                newStylist.FirstName = rdr.GetString(1);
                newStylist.LastName = rdr.GetString(2);
                stylists.Add(newStylist);
            }
            DB.Close(conn);
            return stylists;
        }

        public static Stylist GetStylist(int id)
        {
            MySqlConnection conn = DB.Connection();
            conn.Open();
            var cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"SELECT * FROM stylists WHERE id = @id";
            cmd.Parameters.AddWithValue("@id", id);
            MySqlDataReader rdr = cmd.ExecuteReader() as MySqlDataReader;
            rdr.Read();
            Stylist foundStylist = new Stylist();
            foundStylist.Id = rdr.GetInt32(0);
            foundStylist.FirstName = rdr.GetString(1);
            foundStylist.LastName = rdr.GetString(2);

            DB.Close(conn);
            return foundStylist;
        }

        public static int CreateStylist(string firstName, string lastName)
        {
            MySqlConnection conn = DB.Connection();
            conn.Open();
            var cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"INSERT INTO stylists (first_name, last_Name) VALUES (@firstName, @lastName);";
            MySqlParameter description = new MySqlParameter();
            cmd.Parameters.AddWithValue("@firstName", firstName);
            cmd.Parameters.AddWithValue("@lastName", lastName);
            cmd.ExecuteNonQuery();
            DB.Close(conn);
            return (int) cmd.LastInsertedId;
        }

        public void DeleteStylist()
        {
            MySqlConnection conn = DB.Connection();
            conn.Open();
            var cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"DELETE FROM stylists WHERE id = @stylistId;";
            MySqlParameter description = new MySqlParameter();
            cmd.Parameters.AddWithValue("@stylistId", this.Id);
            cmd.ExecuteNonQuery();
            DB.Close(conn);
            Client.ResetAllByStylistId(this.Id);
        }

        public void EditName(string firstName, string lastName)
        {
            MySqlConnection conn = DB.Connection();
            conn.Open();
            var cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"UPDATE stylists SET first_name = @firstName, last_name = @lastName WHERE id = @stylistId;";
            MySqlParameter description = new MySqlParameter();
            cmd.Parameters.AddWithValue("@stylistId", Id);
            cmd.Parameters.AddWithValue("@firstName", firstName);
            cmd.Parameters.AddWithValue("@lastName", lastName);
            cmd.ExecuteNonQuery();
            DB.Close(conn);
        }

        public static List<Stylist> GetAllBySpecialty(int specialtyId)
        {
            List<Stylist> stylists = new List<Stylist>{};
            MySqlConnection conn = DB.Connection();
            conn.Open();
            var cmd = conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"SELECT DISTINCT stylists.* FROM specialties JOIN specialties_stylists ON (specialties.id = specialties_stylists.specialty_id) JOIN stylists ON (specialties_stylists.stylist_id = stylists.id) WHERE specialty_id = @specialtyId;";
            cmd.Parameters.AddWithValue("@specialtyId", specialtyId);
            MySqlDataReader rdr = cmd.ExecuteReader() as MySqlDataReader;
            while(rdr.Read())
            {
                Stylist newStylist = new Stylist();
                newStylist.Id = rdr.GetInt32(0);
                newStylist.FirstName = rdr.GetString(1);
                newStylist.LastName = rdr.GetString(2);
                stylists.Add(newStylist);
            }
            DB.Close(conn);
            return stylists;
        }
    }
}

HairSalon/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers
{
    public class ClientController : Controller
    {
        public IActionResult Index()
        {
            List<Client> clients = Client.GetAll();
            return View(clients);
        }

        [HttpPost("/Client/New/{stylistId}")]
        public IActionResult Create(int stylistId, string firstName, string lastName)
        {
            int clientId = Client.CreateClient(stylistId, firstName, lastName);
            return RedirectToAction("Show", new {clientId = clientId});
        }

        public IActionResult New()
        {
            return View();
        }

        [HttpGet("/client/show/{clientId}")]
        public IActionResult Show(int clientId)
        {
            Client client = Client.GetClient(clientId);
            if(client.StylistId != 0)
            {
                ViewBag.Stylist = Stylist.GetStylist(client.StylistId);
            }
            else
            {
                ViewBag.AllStylists = Stylist.GetAll();
            }
            return View(client);
        }

        public IActionResult Destroy(int clientId)
        {
            Client.GetClient(clientId).DeleteClient();
            return RedirectToAction("Index");
        }

        public IActionResult DestroyAll()
        {
            Client.ClearAllClients();
            return RedirectToAction("Index");
        }

        public IActionResult UpdateStylist(int stylistId, int clientId)
        {
            Client.GetClient(clientId).UpdateStylistId(stylistId);
            return RedirectToAction("Show", new {clientId = clientId});
        }

        [HttpGet("/client/show/{id}/edit")]
        public IActionResult Edit(int id)
        {
            Client client = Client.GetClient(id);
            return View(client);
        }

        public IActionResult Update(string firstName, string lastName, string phone, int clientId)
        {
            Client.GetClient(clientId).EditClientInfo(firstName, lastName, phone);
            return RedirectToAction("Show", new{clientId = clientId});
        }
    }
}

HairSalon/Controllers/StylistController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers
{
    public class StylistController : Controller
    {
        public IActionResult Index()
        {
            List<Stylist> stylists = Stylist.GetAll();
            return View(stylists);
        }

        public IActionResult Create(string firstName, string lastName)
        {
            int id = Stylist.CreateStylist(firstName, lastName);
            return RedirectToAction("Show", new {id=id});
        }

        public IActionResult New()
        {
            return View();
        }

        [HttpGet("/stylist/show/{id}")]
        public IActionResult Show(int id)
        {
            Dictionary<string, object> model = new Dictionary<string, object>{};
            model.Add("clients", Client.GetAllByStylist(id));
            model.Add("stylist", Stylist.GetStylist(id));
            model.Add("specialties", Specialty.GetAllByStylist(id));
            model.Add("allSpecialties", Specialty.GetAll());
            return View(model);
        }

        [HttpGet("/stylist/show/{id}/edit")]
        public IActionResult Edit(int id)
        {
            Stylist stylist = Stylist.GetStylist(id);
            return View(stylist);
        }

        public IActionResult Update(string firstName, string lastName, int id)
        {
            Stylist.GetStylist(id).EditName(firstName, lastName);
            return RedirectToAction("Show", new {id = id});
        }

        public IActionResult UpdateSpecialty(int specialtyId, int stylistId)
        {
            Specialty.AddStylist(stylistId, specialtyId);
            return RedirectToAction ("Show", new {id = stylistId});
        }

        public IActionResult Destroy(int stylistId)
        {
            Stylist.GetStylist(stylistId).DeleteStylist();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Views/Stylist/Edit.cshtml
<!-- stylist/edit.cshtml -->
@{
    ViewData["Page"] = "Edit Stylist";
}

<h2>Edit Stylist Information:</h2>

<form asp-controller="Stylist" asp-action="Update" method="post">
    <input type="hidden" name="id" value=@Model.Id>
  <div class="">
    <label for="firstName">First Name</label>
    <input type="text" name="firstName" value=@Model.FirstName>
  </div>
  <div class="">
    <label for="lastName">Last Name</label>
    <input type="text" name="lastName" value=@Model.LastName>
  </div>
  <button type="submit">Update Stylist</button>
</form>

HairSalon/Views/Stylist/Index.cshtml
<!-- stylist/index.cshtml -->

@{
    ViewData["Page"] = "All Stylists";
}

<div >
<h2>Stylists:</h2>

      @foreach(Stylist stylist in Model)
      {
        <p><a asp-controller="stylist" asp-action="Show" asp-route-id="@stylist.Id">@stylist.FirstName @stylist.LastName</a></p>
      }
</div>

@section NavLink {
      <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Stylist" asp-action="Index">Stylists</a>
      </li>
      <li class="nav-item">
          <a class="nav-link text-dark new-stylist" asp-area="" asp-controller="Stylist" asp-action="New">Add New Stylist</a>
      </li>
}

HairSalon/Views/Stylist/New.cshtml
<!-- stylist/new.cshtml -->
@{
    Layout = "_Layout";
    ViewData["Page"] = "New Stylist";
}

<h2>Enter New Stylist Information:</h2>

<form asp-controller="Stylist" asp-action="Create" method="post">
  <div class="">
    <label for="firstName">First Name</label>
    <input type="text" name="firstName">
  </div>
  <div class="">
    <label for="lastName">Last Name</label>
    <input type="text" name="lastName">
  </div>

  <button type="submit">Save Stylist</button>
</form>

HairSalon/Views/Stylist/Show.cshtml
<!-- stylist/show.cshtml -->
@{
    ViewData["Page"] = @Model["stylist"].FirstName + "'s Page";
}
<div>
    <div class="pageHead">
        <div>
            <h3>@Model["stylist"].FirstName @Model["stylist"].LastName</h3>
            <form asp-controller="stylist" asp-action="updateSpecialty" method="post">
                <input type="hidden" name="stylistId" value=@Model["stylist"].Id>
                <select name="specialtyId">
                    @foreach(Specialty specialty in Model["allSpecialties"])
                    {
                        <option value=@specialty.Id>@specialty.Name</option>
                    }
                </select>
                <button class="btn btn-dark" type="submit">Add Specialty</button>
            </form>
        </div>
        <div class="editButtons">
            <a class="btn btn-dark" href="/stylist/show/@Model["stylist"].Id/edit">Edit Stylist</a>
            <form asp-controller="stylist" asp-action="destroy">
                <input type="hidden" name="stylistId" value= @Model["stylist"].Id>
                <button class="btn btn-danger" type="submit">Delete Stylist</button>
            </form>
        </div>
    </div>

    @if(Model["specialties"].Count !=0)
    {
        <p>Specialties: </p>
        <ul class="specialtyList">
            @foreach(Specialty specialty in Model["specialties"])
            {
                <li><a asp-controller="specialty" asp-action="show" asp-route-id=@specialty.Id>@specialty.Name</a></li>
            }
        </ul>
    }

    @if(Model["clients"].Count != 0)
    {
        <p>Client List:</p>
        <ul class="client-list">
        @foreach(Client client in @Model["clients"])
        {
            <li><a asp-controller="client" asp-action="show" asp-route-clientId=@client.Id>@client.FirstName @client.LastName</a></li>
        }
        </ul>
    }
    else
    {
        <p>This stylist currently has no clients</p>
    }
</div>

@section NavLink {
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Stylist" asp-action="Index">Stylists</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark new-stylist" asp-controller="Client" asp-action="New" asp-route-id=@Model["stylist"].Id >Add New Client</a>
    </li>
}